# Generated by Django 3.0.2 on 2020-01-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagel',
            fields=[
                ('idBagel', models.AutoField(primary_key=True, serialize=False)),
                ('typePain', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('dateCreation', models.DateTimeField(verbose_name='date ojd')),
            ],
        ),
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('idComplement', models.AutoField(primary_key=True, serialize=False)),
                ('nomComplement', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=100)),
                ('dateCommande', models.DateTimeField(verbose_name='la date')),
                ('bagel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Bagel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.AddField(
            model_name='bagel',
            name='complement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Complement'),
        ),
    ]
